services:
  open-when-db:
    image: postgres:12.6
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - database
  open-when-backend:
    build:
      context: ./backend
      target: dev
    env_file: .env
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    depends_on:
      - open-when-db
    networks:
      - database
      - nginx
  open-when-nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - open-when-backend
    networks:
      - nginx
  open-when-frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:

networks:
  database:
  nginx:
